# Generated by Django 2.2.2 on 2019-07-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonconfig',
            name='onlyShowWinnersTabular',
            field=models.BooleanField(default=True),
        ),
    ]
