# Generated by Django 2.2.3 on 2019-10-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_jsonconfig_onlyshowwinnerstabular'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonconfig',
            name='doHideOverflowAndEliminated',
            field=models.BooleanField(default=False),
        ),
    ]
