# Generated by Django 2.2.3 on 2019-10-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('visualizer', '0004_jsonconfig_dousehorizontalbargraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonconfig',
            name='hideTransferlessRounds',
        ),
        migrations.AddField(
            model_name='jsonconfig',
            name='excludeFinalWinnerAndEliminatedCandidate',
            field=models.BooleanField(default=False),
        ),
    ]
