# Generated by Django 2.2.3 on 2019-10-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('visualizer', '0006_jsonconfig_horizontalsankey'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonconfig',
            name='hideSankey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jsonconfig',
            name='hideTabular',
            field=models.BooleanField(default=False),
        ),
    ]
