# Generated by Django 2.2.10 on 2020-05-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0007_auto_20191030_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonconfig',
            name='rotateNames',
            field=models.BooleanField(default=True),
        ),
    ]
