# Generated by Django 2.2.10 on 2020-06-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0008_auto_20200517_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonconfig',
            name='doDimPrevRoundColors',
            field=models.BooleanField(default=False),
        ),
    ]
