# Generated by Django 2.2.13 on 2020-07-10 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visualizer', '0009_jsonconfig_dodimprevroundcolors'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonconfig',
            name='owner',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='this_users_jsons',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
