# Generated by Django 3.0.8 on 2020-07-23 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        ('visualizer', '0011_auto_20200717_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonconfig',
            name='movieHorizontal',
        ),
        migrations.RemoveField(
            model_name='jsonconfig',
            name='movieVertical',
        ),
        migrations.DeleteModel(
            name='AutoMovie',
        ),
        migrations.RemoveField(
            model_name='jsonconfig',
            name='isVideoGenerationInProgress',
        ),
        migrations.AddField(
            model_name='jsonconfig',
            name='movieGenerationStatus',
            field=models.IntegerField(
                choices=[
                    (0,
                     'No movie generation has been requested'),
                    (1,
                     'Movie generation has been requested but not started'),
                    (2,
                     'Movie generation task has begun'),
                    (3,
                     'Landscape generation complete, portrait pending'),
                    (4,
                     'Complete')],
                default=0),
        ),
        migrations.AddField(
            model_name='jsonconfig',
            name='movieHorizontal',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='jsonconfig',
            name='movieVertical',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='movie.Movie'),
        ),
    ]
