# Generated by Django 3.0.8 on 2020-07-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0012_auto_20200723_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonconfig',
            name='movieGenerationStatus',
            field=models.IntegerField(
                choices=[
                    (0,
                     'No movie generation has been requested'),
                    (1,
                     'Movie generation has been requested but not started'),
                    (2,
                     'Movie generation task has begun'),
                    (3,
                     'Landscape generation complete, portrait pending'),
                    (4,
                     'Complete'),
                    (5,
                     'Failed')],
                default=0),
        ),
    ]
