# Generated by Django 3.0.8 on 2020-12-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0013_auto_20200726_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonconfig',
            name='doDimPrevRoundColors',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jsonconfig',
            name='doUseHorizontalBarGraph',
            field=models.BooleanField(default=True),
        ),
    ]
