# Generated by Django 3.0.8 on 2020-12-17 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_titleimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visualizer', '0014_auto_20201217_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonconfig',
            name='movieHorizontal',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='movie.Movie'),
        ),
        migrations.AlterField(
            model_name='jsonconfig',
            name='movieVertical',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='movie.Movie'),
        ),
        migrations.AlterField(
            model_name='jsonconfig',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='this_users_jsons',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
