# Generated by Django 3.0.8 on 2021-01-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0016_auto_20201223_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonconfig',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
