# Generated by Django 3.0.8 on 2021-03-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0019_jsonconfig_colortheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonconfig',
            name='doHideOverflowAndEliminated',
        ),
        migrations.AddField(
            model_name='jsonconfig',
            name='doHideSurplusAndEliminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jsonconfig',
            name='eliminationBarColor',
            field=models.IntegerField(choices=[(0, 'Gray'), (1, 'Hidden'), (2, 'Same color of transfer')], default=0),
        ),
        migrations.AlterField(
            model_name='jsonconfig',
            name='colorTheme',
            field=models.IntegerField(choices=[(0, 'Full color spectrum'), (1, 'Purple to orange'), (2, 'Alternating colors')], default=1),
        ),
        migrations.AlterField(
            model_name='jsonconfig',
            name='horizontalSankey',
            field=models.BooleanField(default=True),
        ),
    ]
