# Generated by Django 3.0.8 on 2021-03-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0019_jsonconfig_colortheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonconfig',
            name='colorTheme',
            field=models.IntegerField(choices=[(0, 'Full color spectrum'), (1, 'Purple to orange'), (2, 'Alternating colors')], default=1),
        ),
        migrations.AlterField(
            model_name='jsonconfig',
            name='horizontalSankey',
            field=models.BooleanField(default=True),
        ),
    ]
