# Generated by Django 3.0.8 on 2021-05-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0020_auto_20210306_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonconfig',
            name='showRoundNumbersOnSankey',
            field=models.BooleanField(default=True),
        ),
    ]
