# Generated by Django 3.2.4 on 2021-06-15 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0022_auto_20210515_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageFeaturedElectionColumn',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('title',
                 models.CharField(
                     max_length=128)),
                ('order',
                 models.IntegerField(
                     unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageFeaturedElection',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('title',
                 models.CharField(
                     max_length=128)),
                ('order',
                 models.IntegerField(
                     unique=True)),
                ('column',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='links_in_column',
                     to='visualizer.homepagefeaturedelectioncolumn')),
                ('jsonConfig',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='+',
                     to='visualizer.jsonconfig')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
