# Generated by Django 3.2.4 on 2021-06-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0024_remove_jsonconfig_dohideinactiveballotsandresidualsurplus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonconfig',
            name='textForWinner',
            field=models.IntegerField(
                choices=[
                    (0,
                     'Candidate was elected'),
                    (1,
                     'Candidate won'),
                    (2,
                     'Candidate advanced to the general')],
                default=0),
        ),
    ]
