# Generated by Django 3.2.4 on 2021-10-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0025_jsonconfig_textforwinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonconfig',
            name='isPreferentialBlock',
            field=models.BooleanField(default=False),
        ),
    ]
