# Generated by Django 4.2.2 on 2023-06-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0027_alter_jsonconfig_textforwinner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonconfig',
            name='doUseHorizontalBarGraph',
        ),
        migrations.RemoveField(
            model_name='jsonconfig',
            name='horizontalSankey',
        ),
    ]
