# Generated by Django 3.2.15 on 2022-11-02 16:43

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0027_alter_jsonconfig_textforwinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=2048)),
                ('date', models.DateField()),
                ('listOfElections', sortedm2m.fields.SortedManyToManyField(help_text=None, to='visualizer.JsonConfig')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
