# Generated by Django 4.2.20 on 2025-04-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visualizer", "0028_remove_jsonconfig_dousehorizontalbargraph_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jsonconfig",
            name="customText",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
