# Generated by Django 4.2.22 on 2025-08-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visualizer", "0029_jsonconfig_customtext"),
    ]

    operations = [
        migrations.AddField(
            model_name="jsonconfig",
            name="titleImage",
            field=models.ImageField(null=True, upload_to="titleImages"),
        ),
    ]
