# Generated by Django 4.2.22 on 2025-08-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0030_jsonconfig_titleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonconfig',
            name='doUseDescriptionInsteadOfTimeline',
        ),
        migrations.RemoveField(
            model_name='jsonconfig',
            name='rotateNames',
        ),
    ]
