# Generated by Django 4.2.22 on 2025-10-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0031_remove_jsonconfig_dousedescriptioninsteadoftimeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonconfig',
            name='forceFirstRoundDeterminesPercentages',
            field=models.BooleanField(default=False),
        ),
    ]
