# Generated by Django 4.2.28 on 2026-02-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0032_jsonconfig_forcefirstrounddeterminespercentages'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonconfig',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
