# Generated by Django 4.2.22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0033_add_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonconfig',
            name='hidePie',
            field=models.BooleanField(default=False),
        ),
    ]
