dist: xenial
services:
  - xvfb

git:
  depth: 3

branches:
  only:
  - /.*/

language: python
python:
  - '3.6'

addons:
  chrome: stable
  sauce_connect: true

before_install:
  - ./scripts/install_chromedriver.sh
  - sudo ./scripts/fix-moviepy-on-ubuntu-1604.sh
  # required for pycurl to install
  - sudo apt-get -y install libgnutls28-dev imagemagick ffmpeg

install:
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install -e .
  - pip3 install -r requirements.txt

script:
  - python3 manage.py test
  - ./scripts/test_code_quality.sh
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: elasticbeanstalk
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    region: us-west-1
    app: rcvis
    env: django-env-try2
    on:
      branch: main
    bucket_name: elasticbeanstalk-us-west-1-872212457283
  - provider: elasticbeanstalk
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    region: us-west-1
    app: rcvis
    env: rcvis-staging
    on:
      branch: staging
    bucket_name: elasticbeanstalk-us-west-1-872212457283
