git:
  depth: 3

branches:
  only:
  - /.*/

language: python
python:
  - '3.6'

install:
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install -e .
  - pip3 install -r requirements.txt

script:
  - python3 manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "X/xR5nwQEOvpILxxL6pd1AS/jiFz2in+pBg1huY6Jzi3XW7RAJfFWOsEEYZYUPwPhgtRylnniEyUt8NIOV0CpqwSEaUOfkpcUtSz4iCFbHXSItr2MpEJ4Ltk1MEc7B9zBstlCbKC2o2O0++nGo7HmXbrOsULd+4XbuMiAdqxgZJu226bPE+nKGrTIjLXjpRMENaTUbt+/QZu0oj0ep/q5Br8aR/Bj9WvQkxM2IbiVb//l5dZl5076yc0/sfqkMn6WaWB6Nx+p4TLUNv7XQLwPXF22Zesl/xi+9zYdaCGB/2lIRKqZHGEX48/W301KyMkoXodOCjHGzysob3/EB4XLIuB0LxmUPBWFiZAPFgZUAq4cBydJrIiPdzBPSOwcLWO0mab3qsUqCC17Vdm/NC8Lb+Ux9ahtwbCsMXqHB6lTaAOqFa+EPjkhHMdr/Dir0Ro0qM76BkWLnRLkHCO7rvqDKoqSi514KePj7fKF9WdbEDmh4UpdmNto9WRAbMu98nzrVxiEb/EobimcitgYfx30gfCJVyNN84U1CT65lBbZTNfefop6wyP2FYuoqaESxZYmZ3dLSQZ4GitMV7C17/h60Gg85cbdA2KFTLE1Dsw7a9Mk1JdyfhVAX4mOiWPQTdNutSOrVx4f4d/v6+p3ISWFYuxNsO7YE4fEdk7wyAr3+A="
  secret_access_key:
    secure: "cCQgCXK4IHtTyFxLqPr7Kghl8dplGwgxUJjwO6yDKMRT94Mwn94CUR2U4mD2JqBfPApe//Hyl1ziWAGbE719wK8dpdzNVqxQj9H1H6T99eV9IblUTxHlRuQ2rz+OKrtd/AWkFNtd5TbyXyQcW/2rFxK+rTdhvxJk1UhoEl0EzmWB6Gb5m9+p80UukDia7FhNLOmpNiPJC1n4xLmn8sGCy/Jqv7AbK0/M8HQNI1Pl0B0ywgy0KFH1bI5g6PxlJTILR3mrI8WdaIcYidCsyY+nAvcUT5jr5xz6IJF3iLLQ4lj6Pd9mo4/lWltgRnMNNUO/ZqJ3McW4H05Nf0Rwf15VHOA/rtetdW6gjzpLz6fZQZuF1UzJtU0vG+OBZNkpRDRLPOus3l84QY9aOUsABsmW7ggfZAG8GiJBWKxvDMa/6WPq0f7X8HMlSV7XanQItUqpwqq4AH4ED27034soMTJeSMjbIRrBG2AHiMbs3GXvFyD7ghI5clwwee27rXkmwpCBzQ/F0VSYFQ3HR1PQcJOlf6eoKbpUuxc7Ne9HpaOqTom6qn8XRqxS64NOEg7OioeaBqtNM1AGRdPXltVSeVLbKkj+e/DX0PH39tPUUx7O7hRSl/KI9kaUAJJsjXMAd/yLeBy0yxRSj78QPcUA7i921bb7wsAqO7f2Huv5+m3tyRU="
  region: us-west-1
  app: rcvis
  env: django-env-try2
  on:
    repo: artoonie/rcvis
  bucket_name: elasticbeanstalk-us-west-1-872212457283
