git:
  depth: 3

branches:
  only:
  - /.*/

language: python
python:
  - '3.6'

install:
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install -e .
  - pip3 install -r requirements.txt

script:
  - python3 manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "TS1C9Wh9Waj2G4NZ+FF+ebLQGLkeoEfch8iydItin4raEf8NdqA0ZrmdMzgFMXBi6EiUffPIQvn6jMbbe6yVKtUFZCch/tKukPLpJAiuxhhBykFLAy5uZg8XYRGWGfhTTtweRFqbgzHK/2cNBFN2m7FixKO5smxU1p4wqYeLdGCYhkzxnhJPicHdzDoGMZbIZVDJQzBkT+WlMoSEAdXlgW00WRUQNwUlRgwMf2lFhXe0djvDDNPffpaBoXAFPgASI6UP9qqnzyo7YYB9riyCSBkfF2AbPVF8Cgll/YSVDLSSXEX4QKu8cYIzGtc3OnB8Efk5yINvPg1IdjWHI/VfRg2jGR19xkRpAYHPMU7gLTfLaaP0vOoVvd1V1Q4fIQl6t9RsJ78+T88sBjOeZZrAQC2lTWQm+bj8rs4Kb0ae5DdaJQO3mhvx/NZQvaM2cLs5Pbl6qCbSl6zMuwcF/TBsoLOmUmSJrrzr4p8EwszznDbOz2pnp+++z+2znRVxl7dIey7FahaB8t3IruQnkwf4v7JXEL4o8EE8MAlC6y5NDSiickvK1gXdmXrwZGvCpC6KhW1ohn1FlETEYg6aA+0A1c3iOR/mcm+kETEPUQLnzlimdYdR8CKeRfVRpWNNxk62Ysp1LKGKWHZpi0J8oeA/0Tx2y6OLdT4aQXx/SVw35tQ="
  secret_access_key:
    secure: "jyES10WhQLMU4K70Utb5Zeyg8eI8cB39h9wbBKKHDdSOAnihQBm6kOvU/5XpCSDuAn/xhfldqdlYj7rTLk88MLAAgy5en47XjQePXI/8H8wPgyyX7RGtQMLUau5bRVekbF+GfT1eLhU1L7HthVLa8z6ZdHITZJ0XdZ/dr5QaQY5q6/sGDP0G+agfp7GA4JLsA8TjyDZUF0jQPy50rv+4M3ad9NPKyAQ2+TubiszRwQYnV0FqKCIv0d6ww8b2ITbh8FzWMftnmFgbU4Lx+/+EXuANN/oljp84oBDtpofIZbqcW3s68SdpOw1jTX06Agt3mpl3cJHjBeQv1bofdCThZoCgWE4l//c77QJbXH2A/Ac60Xsk0M0HXDzK53k7YaX1U47AmRUR1EzeLi1Q0DQxzzD7GmgO5MwaDE0en5RMhcoEAtCaQfupr1gcbpAxKVni7cT6Ws9xx2a3xjcJXV48s1S3z7FcU5WnHQHso695DVZqRC1XjwcDB5o0PABlyqlrLMcLgwwM+EFLe9w1KjAtRVIZ8wAKMVCjYmE8Y/Rns4Ux7+eCJRFOxN7pIH5U0HeW2Eh47jvbCp+PYIgv4hrmzz7yQziVA6CmjuF22D/iNXwV1ktOvGc7RvrS8Zzhk2VSE/eDhJevfR1HY9omxlSxonOrXqG/lhmJjEryKqOOTm8="
  region: us-west-1
  app: rcvis
  env: django-env-try2
  on:
    repo: artoonie/rcvis
  bucket_name: elasticbeanstalk-us-west-1-872212457283
