git:
  depth: 3

branches:
  only:
  - /.*/

language: python
python:
  - '3.6'

addons:
  firefox: "latest"

install:
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install -e .
  - pip3 install -r requirements.txt
  - sudo apt-get install geckodriver

script:
  - python3 manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: us-west-1
  app: rcvis
  env: django-env-try2
  on:
    repo: artoonie/rcvis
  bucket_name: elasticbeanstalk-us-west-1-872212457283
