dist: xenial
services:
  - xvfb

env:
  global:
    - MOZ_HEADLESS=1

git:
  depth: 3

branches:
  only:
  - /.*/

language: python
python:
  - '3.6'

addons:
  firefox: "71.0"
  sauce_connect: true

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin/

install:
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install -e .
  - pip3 install -r requirements.txt

script:
  - python3 manage.py test
  - ./validateLinter.sh
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: elasticbeanstalk
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    region: us-west-1
    app: rcvis
    env: django-env-try2
    on:
      branch: master
    bucket_name: elasticbeanstalk-us-west-1-872212457283
  - provider: elasticbeanstalk
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    region: us-west-1
    app: rcvis
    env: rcvis-staging
    on:
      branch: staging
    bucket_name: elasticbeanstalk-us-west-1-872212457283
