git:
  depth: 3

branches:
  only:
  - /.*/

language: python
python:
  - '3.6'

install:
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install -e .
  - pip3 install -r requirements.txt

script:
  - python3 manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "B83UQzcclwP3e3KATBmJnj6mCEATkF1lwTBVyGlkxsmL6vIIFXek2h6vS68aYeTgl0Cxgkdxn74Md44K/MczvwIvsxpTUy6nKl+sZcHO7C8TaF5CniYN01YCEadgtp9/SaVDEuZaa2h7NtwocblJcHLjSWwtOB3U54IyXLjprXDKCbQt5bJQXzh9bb3LxGU+16dA5em8LBAbnQfMRpTOm/Qt2Hn1pNuloshUfq3hE2XaE5ohfyu/FB2rM6kxecKed27Kuhc8jQDx9UPQ0lK470W0aq9zZT6kq+Ud0Ptn9WpHZWz/8I3ZeYjlOqbqNSPVn6XhgOLmWMlmgDn8Z+nq2X4aCdl0sIBazKaw+VUtBBe+V+hVv4DRm0wXmVfIei5M1Li/2SKqQcILEfCXNpo3s27YmSg34CHeenkmaQhHTlKGA+ekUGb8pFcez+Vg3e2YgGSo0FYhZ8QGTDdPfq62DkNj5op8Oe04ZYsEyP7oZvuZ29fmMCmxHEypo3GxrFA2/oD8iaptt9fsvE1C9mLkX9TOP1Fax+DSWqNtlqKtFr+BETcptvHIYwMjyDg57ZxHfhPG5YoajzWv2+F8B6sbeOotmKgIiCgd1Qby8NdnAz1s/fKa20kQj1/EiY3dowVrLVgEfZeuDY5+T+R1ZJSJ55ofU8ZJ1odSniEDp+81Gj4="
  secret_access_key:
    secure: "f5WLAnrw/l8kpYT9b319vf0l9LMlLeZtfNYDwgdooxxfCZqgYcwwq9odO4BvlvylO99X6d07lTqIuqSE/BzAA9sEqueibjSBWgLX4bFfu8a7Di9ovY9aYUca8yzZME6GhcQXe95EmyZf6QD7/vbRObUV9gebOMtLzhk2PpiMhl8LVv1QNdrP4G4mHM26LpONnH6lr1NdHaRlPucKWxLakFsGeIgvP4hr/2tH3UGiEezvUKTm8zahvI53NhGhWE8aGh8vxU/9ky0bTPGiqEV/QIMfQP7S4ozniZPrkmfNgV0fbwlVoZUMe2WKHsAdAXxip3tPsfDDsh67Lsna3O2dX5faioluewEov0aCRVVgLOJYgUDlCaHDTWQrHs11ZPf4/Xn9HvpAwrskcjOhwabWzQOtbG2HYOO69StSR4Gp+qnfw9kic9lQNe8yzaiYfzgt4QdwupOhJFO/hN5nU6kGzp4gfpDNuvVDfAxZP8wI7/bFB3GlnhwT21eI22tAK2E/SsK6oSQoxv9lS+6v4+x746NVFR6MAZixUmV3dOM/emATU12R/kNIQlzlnxeDfRT6qqQ0E8OkraWaVwVhOGUuKskmk+DBiY3oVVG6LBoTAy5nwV77t9YRQ9H3MmDffONneaBTM0waQuMDiYQH1Tcd22p7o2GLS9X5eD3UBVcg5WU="
  region: us-west-1
  app: rcvis
  env: django-env-try2
  on:
    repo: artoonie/rcvis
  bucket_name: elasticbeanstalk-us-west-1-872212457283
