git:
  depth: 3

branches:
  only:
  - /.*/

language: python
python:
  - '3.6'

install:
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install -e .
  - pip3 install -r requirements.txt

script:
  - python3 manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "lbsLn565Dyq3sOhiQJ3QNXvXMTkmzdmRKIxvcmIwcQmSKEIcQ0WnuKfSyAr4PSrUEF+EUyfHci8Rr4tqMOEsrU9VaS+BJdH4Q+ilQBM/ondTRBJ3P4GmQNgemzGHeSkmj7iPCBICvjwWaCQ5FW8b5/WYSk7I2fag6fGIqQJ9iXWm01xVcFlpTNoWWX0Ly6ygy0rVTJqejMyDpvyx7w/bZicV5g2oBtOL9fTXKutwDrlL0v4y1mPnWvZcfzFKdcrtIwFHaa77xDZP3sU6SrLIiG8uB5JW35Fixm2xrt2SuyufIYgKmgZKH/LmnDekqdIADn+0qR22t3pXJF7pvQ/1h91uMMw3YPPRM9bqa4MDAq60vsaUY/eH1UL53INi9gYSvgbvgq143xufuyeYzu5IbODu12RwoTlYnizJT46WOoLtnGdQTtQ/izTKVGBEpevqfY6FUY/tCGyc2ykGJH9JWiJsxK8N40yn1kMrOy3fe5npf+qtVBKwyQ/lrpp2dcxTTa6FUrCNX21V376ZNDtXiMb3qFVRR5xij0cXErooWSYu0rVnoXnbAb2CizAyE1AQLJlrHWSLpJmPf0FoFUVO2F4HBbJafIDJaTdfa6Q259HbNcbbnnNsPRvqzBagln/sbbMGYtDDRqb4OC8ADYy0KYxE3VRSxyIQQpuBsKcStA8="
  secret_access_key:
    secure: aBX7oyXFBibbPZzvf2qS3hN22ZhRS7X4RaqR70HWHEeWx9SXaXyCVT8tz+Vaoh8qE2qckiFovfyae1O0sYqeZoWZhxz+P/uuZrs8OUJ3Hm/vV/FhgND5x6oWHJfqk8DmRMIIu8xL/p1w74zC9KY8DxdN/W+lwJe4Kf36tXx3CKMv/gPyr3fBDHIWUaIh5wWMQLPJJY5LQG8Z3N0KK+BKw0g5RSJ6vqhGL5J8iVezRD/A8yrecO8XhxnydeHT9uBeYX1RQZgEl745rp6GNCHRBh74FAhSrKpY5LIAuUz/s3uoYd3pTg0GmH9o9vOmfY5oLkuu/zIQPRb4w9bKYeHrsj+CLVpC9KG6a1L7xEX+6p7aMVxae2EOcz+ksuylCKhGSwiRD0W8QmcqlZAtwP6E9Ydrx29jtpElcSuO4xmyOI9lJpwtTl60IuzG1V5hgA7XxgxEjSHZ7Zbh0hRm2q9wqYzw8m/bYivDEtKQ8+eRijc4489LfNWUuR/01nEjTx+pVgQvLQGi/HpIw7w5/+m4a/vyU2B+vbLHkdo435mgb+u/vBwFIwu1Izb+x7NJaeEqb3B/pJ06dxt49CVx0RyoK6DSVyy5SZFqj0/uKUF8t94ACKuyKoNooQYW7t9NWRMh42iO0bBNEFaeexH6lK4VJr4bwwsOsdcExDjwiJeQgMA=
  region: us-west-1
  app: rcvis
  env: django-env-try2
  on:
    repo: artoonie/rcvis
