version: "3"

services:
  nginx:
    volumes:
      - .:/code
    network_mode: "host"
    logging:
      driver: syslog
  web:
    volumes:
      - .:/code
    network_mode: "host"
    logging:
      driver: syslog
  moviegen:
    volumes:
      - .:/code
    network_mode: "host"
    logging:
      driver: syslog
