FROM python:3
ENV PYTHONUNBUFFERED=1
RUN mkdir /code
WORKDIR /code
COPY infra/requirements*.txt /code/
RUN pip install -r requirements.txt
COPY rcvis visualizer movie common static templates manage.py /code/
CMD python manage.py runserver 0.0.0.0:8000
