FROM ubuntu:focal
ENV PYTHONUNBUFFERED=1

# Update
RUN apt-get -y update && apt-get -y upgrade

# First install tzdata and ensure it doesn't ask for a timezone
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata

# Then install all other deps
RUN apt-get install -y \
    wget \
    curl \
    libcurl4-openssl-dev \
    wget \
    xvfb \
    python3-pip \
    unzip \
    libgnutls28-dev \
    libgconf-2-4 \
    ffmpeg \
    libglib2.0-0 \
    libnss3 \
    libgconf-2-4 \
    libfontconfig1 \
    supervisor \
    imagemagick \
    libssl-dev

# Set up the Chrome PPA
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list && \
    apt-get -y update && \
    apt-get install -y google-chrome-stable

# Set up Chromedriver Environment variables
ENV CHROMEDRIVER_VERSION 2.36
ENV CHROMEDRIVER_SHA256 2461384f541346bb882c997886f8976edc5a2e7559247c8642f599acd74c21d4
ENV CHROMEDRIVER_DIR /usr/bin

# Download and install Chromedriver
RUN curl -SLO "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" \
  && echo "$CHROMEDRIVER_SHA256  chromedriver_linux64.zip" | sha256sum -c - \
  && unzip "chromedriver_linux64.zip" -d $CHROMEDRIVER_DIR \
  && rm "chromedriver_linux64.zip"

# Put Chromedriver into the PATH and set its display
ENV PATH $CHROMEDRIVER_DIR:$PATH
ENV DISPLAY :99

RUN mkdir /code /var/log/supervisord /var/run/dbus/
WORKDIR /code

ADD infra/supervisord.conf /etc/supervisor/supervisord.conf
ADD scripts/fix-moviepy-on-ubuntu.sh /tmp/fix-moviepy-on-ubuntu.sh

COPY infra/requirements*.txt /code/
RUN pip3 install -r requirements.txt && \
    pip3 install pycurl --global-option="--with-openssl" && \
    /tmp/fix-moviepy-on-ubuntu.sh

# Only copy directories needed to run, not README/test/etc:
COPY rcvis /code/rcvis
COPY visualizer /code/visualizer
COPY movie /code/movie
COPY common /code/common
COPY static /code/static
COPY templates /code/templates
COPY manage.py /code/

CMD supervisord -c /etc/supervisor/supervisord.conf
