FROM ubuntu:focal
ENV PYTHONUNBUFFERED=1

# Update
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y python3-pip gunicorn

RUN mkdir /code
WORKDIR /code

COPY infra/requirements*.txt /code/
RUN pip3 install -r requirements.txt

# Only copy directories needed to run, not README/test/etc:
COPY rcvis /code/rcvis
COPY visualizer /code/visualizer
COPY movie /code/movie
COPY common /code/common
COPY static /code/static
COPY templates /code/templates
COPY manage.py /code/

CMD gunicorn rcvis.wsgi:application --bind 0.0.0.0:8000
