version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 0.5GB
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-0c9c78d3cc8802762"
        - "subnet-05e11a40bf1fbbe4c"
      security_groups:
        - "sg-078f50859799967f9"
      assign_public_ip: DISABLED
