# Generated by Django 3.2.15 on 2022-11-06 23:15

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0001_initial'),
        ('visualizer', '0027_alter_jsonconfig_textforwinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapableElectionPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=2048)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('areResultsCertified', models.BooleanField(default=False)),
                ('listOfScrapers', sortedm2m.fields.SortedManyToManyField(help_text=None, to='scraper.Scraper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectionPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=2048)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('listOfElections', sortedm2m.fields.SortedManyToManyField(help_text=None, to='visualizer.JsonConfig')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
