# Generated by Django 3.2.5 on 2021-11-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0027_alter_jsonconfig_textforwinner'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='downloadedRawData',
            field=models.ManyToManyField(to='visualizer.JsonConfig'),
        ),
    ]
