# Generated by Django 3.2.5 on 2022-02-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_downloadedrawdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
