# Generated by Django 3.0.8 on 2020-07-25 20:23

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200724_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieFile',
            field=models.FileField(
                max_length=512,
                upload_to='movies'),
        ),
        migrations.AlterField(
            model_name='texttospeechcachedfile',
            name='audioFile',
            field=models.FileField(
                max_length=512,
                storage=movie.models.SpeechSynthStorage(),
                upload_to='speech-synth'),
        ),
    ]
