# Generated by Django 3.0.8 on 2020-08-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200725_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='titleImage',
            field=models.ImageField(null=True, upload_to='movieTitleImages'),
        ),
    ]
