# Generated by Django 4.2.2 on 2023-06-15 20:36

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0028_remove_jsonconfig_dousehorizontalbargraph_and_more'),
        ('scraper', '0002_multiscraper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiscraper',
            name='listOfElections',
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True,
                help_text=None,
                related_name='+',
                to='visualizer.jsonconfig'),
        ),
    ]
